name: pie
description: "PIE Parking uses QR Codes to make parking ticketless and as easy as..."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  http: ^1.5.0

  flutter_spinkit: ^5.2.2

  shared_preferences: ^2.5.3

  crypto: ^3.0.6

  font_awesome_flutter: ^10.10.0

  mobile_scanner: ^7.1.3

  intl: ^0.20.2

  payfast: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  #To add assets to your application, add an assets section, like this:
  assets:
    - images/

  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
    - family: Poppins ExtraLight
      fonts:
        - asset: fonts/Poppins-ExtraLight.ttf